# Generated by Django 4.0 on 2022-05-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refdoc',
            name='contact',
            field=models.IntegerField(blank=True),
        ),
    ]
