# Generated by Django 4.0.1 on 2022-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdoc', '0003_alter_refdoc_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refdoc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='refdoc',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='refdoc',
            name='profession',
        ),
        migrations.AddField(
            model_name='refdoc',
            name='details',
            field=models.TextField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='refdoc',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
