# Generated by Django 4.0.1 on 2022-06-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdoc', '0004_remove_refdoc_address_remove_refdoc_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='refdoc',
            name='gid',
            field=models.IntegerField(default=0),
        ),
    ]
