# Generated by Django 4.0.1 on 2022-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdoc', '0005_doc_group_refdoc_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refdoc',
            name='name',
            field=models.TextField(default=0, max_length=25),
        ),
    ]
