# Generated by Django 4.0.1 on 2022-06-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refdoc', '0006_alter_refdoc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refdoc',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdoc.doc_group'),
        ),
    ]
