# Generated by Django 4.0.1 on 2022-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='d_name',
        ),
        migrations.AddField(
            model_name='disease',
            name='disease',
            field=models.TextField(default=0, max_length=15),
        ),
    ]
