# Generated by Django 4.0.1 on 2022-05-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('medicine_power', models.CharField(max_length=30)),
                ('medicine_price', models.IntegerField(blank=True)),
            ],
        ),
    ]
