# Generated by Django 4.0.1 on 2022-05-24 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('tfees', models.IntegerField(default=0)),
                ('tpaid', models.IntegerField(default=0)),
                ('tleft_from_patient', models.IntegerField(default=0)),
                ('tleft_from_doc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='patient_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('rperson', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('member', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient_health_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=30)),
                ('diagnostic', models.CharField(max_length=30)),
                ('prescription', models.CharField(max_length=30)),
                ('report', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('fees', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('left_from_patient', models.IntegerField(default=0)),
                ('left_from_doc', models.IntegerField(default=0)),
            ],
        ),
    ]
