# Generated by Django 4.0.1 on 2022-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_health_detail',
            name='prescription',
            field=models.TextField(max_length=30),
        ),
    ]
