# Generated by Django 4.0.1 on 2022-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0002_alter_patient_health_detail_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_group',
            name='tfees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_group',
            name='tleft_from_doc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_group',
            name='tleft_from_patient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_group',
            name='tpaid',
            field=models.IntegerField(default=0),
        ),
    ]
