# Generated by Django 4.0.1 on 2022-05-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0003_patient_group_tfees_patient_group_tleft_from_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginmodule.patient_detail'),
        ),
    ]
