# Generated by Django 4.0.1 on 2022-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0004_alter_account_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
    ]
