# Generated by Django 4.0.1 on 2022-05-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0006_remove_account_id_alter_account_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loginmodule.patient_detail'),
        ),
    ]
