# Generated by Django 4.0.1 on 2022-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0007_alter_account_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_detail',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='patient_detail',
            name='note',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patient_detail',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient_detail',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient_detail',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient_detail',
            name='rperson',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_detail',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
