# Generated by Django 4.0.1 on 2022-06-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0010_patient_health_detail_paid_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_health_detail',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginmodule.patient_detail'),
        ),
    ]
